myapp/urls.py
from django.urls import path
from myapp import views

app_name='myapp'

urlpatterns = [
	# path('',views.index,name='index'),
	path('',views.user_login,name='user_login'),
	path('block/',views.block,name='block'),
	# path('lecture/',views.lecture,name='lecture'),
	# path('labs/',views.labs,name='labs')
	path('lecture/booking/',views.booking,name='booking')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from myapp import views

urlpatterns = [
	path('',views.user_login,name='user_login'),
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls')),
    path('lecture/',views.lecture,name='lecture'),
    path('logout/',views.user_logout,name='logout'),
    path('build1/',views.build1,name='build1'),
    path('booking/',views.booking,name='booking'),
]

myapp/forms.py
from django import forms
from django.contrib.auth.models import User
from myapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
	

myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.utils import timezone
import datetime
import calendar
from datetime import datetime,date
from myapp.abc import findDay 
from django.views.generic import ListView
from myapp.models import t8_9,t9_10,t10_11,t11_12,t12_1,t1_2,t2_3,t3_4,t4_5,update
from django.contrib import messages
# Create your views here.

# def index(request):
# 	return render(request,'myapp/index.html')
@login_required
def block(request):
	return render(request,'myapp/blocks.html')
@login_required
def build1(request):
	if request.method=='POST':
		if 'NAB' in request.POST:
			blockis='NAB'
		if 'Electrical' in request.POST:
			blockis='Electrical'
		if 'Production' in request.POST:
			blockis='Production'
		if 'Metta' in request.POST:
			blockis='Metta'
		if 'Aero' in request.POST:
			blockis='Aero'
		if 'Audi' in request.POST:
			blockis='Audi'
		block={'block_is':blockis}	

		return render(request,'myapp/build1.html',context=block)
@login_required
def booking(request):
	if request.method=='POST':
		day=request.POST.get('day_is')
		time=request.POST.get('time_is')
		date=request.POST.get('date_is')
		hall=request.POST.get('hall_is')
		room=request.POST.get('lecture_hall')
		blockname=request.POST.get('block_is')
		buttonis=request.POST.get('button1')
		search_type='exact'
		search_string=day+'__'+search_type
		global u
		status='empty'
		if(buttonis=='Book'):
			status=u
		if(time=='1'):
			get_name=t8_9.objects.filter(halls__exact=room).update(**{day:status})
		elif(time=='2'):
			get_name=t9_10.objects.filter(halls__exact=room).update(**{day:status})
		elif(time=='3'):
			get_name=t10_11.objects.filter(halls__exact=room).update(**{day:status})
		elif(time=='4'):
			get_name=t11_12.objects.filter(halls__exact=room).update(**{day:status})
		elif(time=='5'):
			get_name=t12_1.objects.filter(halls__exact=room).update(**{day:status})
		elif(time=='6'):
			get_name=t1_2.objects.filter(halls__exact=room).update(**{day:status})
		elif(time=='7'):
			get_name=t2_3.objects.filter(halls__exact=room).update(**{day:status})
		elif(time=='8'):
			get_name=t3_4.objects.filter(halls__exact=room).update(**{day:status})
		elif(time=='9'):
			get_name=t4_5.objects.filter(halls__exact=room).update(**{day:status})
		
			
		block={'block_is':blockname,'abc':True}
		messages.success(request,"You have Successfully processed your request")
		return render(request,'myapp/build1.html',context=block)

			









@login_required
def lecture(request):
	# def findDay(date): 
	# 	day, month, year = (int(i) for i in date.split('/'))     
	# 	born = datetime.date(year, month, day) 
	# 	return born.strftime("%A")
	if request.method=='POST':	
		global u
		if 'L' in request.POST or 'L_cancel' in request.POST:

			date=request.POST.get('date1')
			time=request.POST.get('time1')
			blockname=request.POST.get('blockname')


			date=str(date)
			block={'block_is':blockname,'abc':False}
			if(date==""):
				messages.error(request,"You can't leave the date field empty!!")
				return render(request,'myapp/build1.html',context=block)
			date_format='%Y-%m-%d'
			df1='%m/%d/%Y'
			a = datetime.strptime(str(datetime.now().date()), date_format)
			b=datetime.strptime(str(date),df1)
			delta=b-a
			day1=(findDay(date))
			day1=day1.lower()
			hall='L'
			
			if(delta.days<0):
				messages.error(request,"You can't Book/Cancel the class in past")
				return render(request,'myapp/build1.html',context=block)
			elif(delta.days>=7):
				messages.error(request,"You are thinking of too far.You can Book/Cancel classes of only one week")
				return render(request,'myapp/build1.html',context=block)
			elif(day1=='saturday' or day1=='sunday'):
				messages.error(request,"It's your holiday,enjoy!!!")
				return render(request,'myapp/build1.html',context=block)
			
			else:
				date1=update.objects.filter(day__exact=day1)
				c='abc'
				for j in date1:
					c=datetime.strptime(str(j.date),df1)
				diff=b-c
				if(diff.days!=0):
					if(day1=='tuesday'):
						original=t8_9.objects.all()
						for i in original:
							i.tuesday=i.tuesday_copy
							i.save(update_fields=['tuesday'])
						original=t9_10.objects.all()
						for i in original:
							i.tuesday=i.tuesday_copy
							i.save(update_fields=['tuesday'])
						original=t10_11.objects.all()
						for i in original:
							i.tuesday=i.tuesday_copy
							i.save(update_fields=['tuesday'])
						original=t11_12.objects.all()
						for i in original:
							i.tuesday=i.tuesday_copy
							i.save(update_fields=['tuesday'])
						original=t12_1.objects.all()
						for i in original:
							i.tuesday=i.tuesday_copy
							i.save(update_fields=['tuesday'])
						original=t1_2.objects.all()
						for i in original:
							i.tuesday=i.tuesday_copy
							i.save(update_fields=['tuesday'])
						original=t2_3.objects.all()
						for i in original:
							i.tuesday=i.tuesday_copy
							i.save(update_fields=['tuesday'])
						original=t3_4.objects.all()
						for i in original:
							i.tuesday=i.tuesday_copy
							i.save(update_fields=['tuesday'])
						original=t4_5.objects.all()
						for i in original:
							i.tuesday=i.tuesday_copy
							i.save(update_fields=['tuesday'])
					elif (day1=='monday'):
						original=t8_9.objects.all()
						for i in original:
							i.monday=i.monday_copy
							i.save(update_fields=['monday'])
						original=t9_10.objects.all()
						for i in original:
							i.monday=i.monday_copy
							i.save(update_fields=['monday'])
						original=t10_11.objects.all()
						for i in original:
							i.monday=i.monday_copy
							i.save(update_fields=['monday'])
						original=t11_12.objects.all()
						for i in original:
							i.monday=i.monday_copy
							i.save(update_fields=['monday'])
						original=t12_1.objects.all()
						for i in original:
							i.monday=i.monday_copy
							i.save(update_fields=['monday'])
						original=t1_2.objects.all()
						for i in original:
							i.monday=i.monday_copy
							i.save(update_fields=['monday'])
						original=t2_3.objects.all()
						for i in original:
							i.monday=i.monday_copy
							i.save(update_fields=['monday'])
						original=t3_4.objects.all()
						for i in original:
							i.monday=i.monday_copy
							i.save(update_fields=['monday'])
						original=t4_5.objects.all()
						for i in original:
							i.monday=i.monday_copy
							i.save(update_fields=['monday'])
					elif (day1=='wednesday'):
						original=t8_9.objects.all()
						for i in original:
							i.wednesday=i.wednesday_copy
							i.save(update_fields=['wednesday'])
						original=t9_10.objects.all()
						for i in original:
							i.wednesday=i.wednesday_copy
							i.save(update_fields=['wednesday'])
						original=t10_11.objects.all()
						for i in original:
							i.wednesday=i.wednesday_copy
							i.save(update_fields=['wednesday'])
						original=t11_12.objects.all()
						for i in original:
							i.wednesday=i.wednesday_copy
							i.save(update_fields=['wednesday'])
						original=t12_1.objects.all()
						for i in original:
							i.wednesday=i.wednesday_copy
							i.save(update_fields=['wednesday'])
						original=t1_2.objects.all()
						for i in original:
							i.wednesday=i.wednesday_copy
							i.save(update_fields=['wednesday'])
						original=t2_3.objects.all()
						for i in original:
							i.wednesday=i.wednesday_copy
							i.save(update_fields=['wednesday'])
						original=t3_4.objects.all()
						for i in original:
							i.wednesday=i.wednesday_copy
							i.save(update_fields=['wednesday'])
						original=t4_5.objects.all()
						for i in original:
							i.wednesday=i.wednesday_copy
							i.save(update_fields=['wednesday'])	
					elif (day1=='thursday'):
						original=t8_9.objects.all()
						for i in original:
							i.thursday=i.thursday_copy
							i.save(update_fields=['thursday'])
						original=t9_10.objects.all()
						for i in original:
							i.thursday=i.thursday_copy
							i.save(update_fields=['thursday'])
						original=t10_11.objects.all()
						for i in original:
							i.thursday=i.thursday_copy
							i.save(update_fields=['thursday'])
						original=t11_12.objects.all()
						for i in original:
							i.thursday=i.thursday_copy
							i.save(update_fields=['thursday'])
						original=t12_1.objects.all()
						for i in original:
							i.thursday=i.thursday_copy
							i.save(update_fields=['thursday'])
						original=t1_2.objects.all()
						for i in original:
							i.thursday=i.thursday_copy
							i.save(update_fields=['thursday'])
						original=t2_3.objects.all()
						for i in original:
							i.thursday=i.thursday_copy
							i.save(update_fields=['thursday'])
						original=t3_4.objects.all()
						for i in original:
							i.thursday=i.thursday_copy
							i.save(update_fields=['thursday'])
						original=t4_5.objects.all()
						for i in original:
							i.thursday=i.thursday_copy
							i.save(update_fields=['thursday'])	
					elif (day1=='friday'):
						original=t8_9.objects.all()
						for i in original:
							i.friday=i.friday_copy
							i.save(update_fields=['friday'])
						original=t9_10.objects.all()
						for i in original:
							i.friday=i.friday_copy
							i.save(update_fields=['friday'])
						original=t10_11.objects.all()
						for i in original:
							i.friday=i.friday_copy
							i.save(update_fields=['friday'])
						original=t11_12.objects.all()
						for i in original:
							i.friday=i.friday_copy
							i.save(update_fields=['friday'])
						original=t12_1.objects.all()
						for i in original:
							i.friday=i.friday_copy
							i.save(update_fields=['friday'])
						original=t1_2.objects.all()
						for i in original:
							i.friday=i.friday_copy
							i.save(update_fields=['friday'])
						original=t2_3.objects.all()
						for i in original:

templates/myapp/build1.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Choose Block</title>

	<link rel="stylesheet" type="text/css" href="{% static 'myapp\bootstrap-4.3.1-dist\css\bootstrap.css' %}" >
	<link rel="stylesheet" type="text/css" href="{% static 'myapp\fontawesome-free-5.11.2-web\css\all.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'myapp\build1.css'%}">
	<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" /> -->
	<!-- <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous"> -->
	
  <!-- <title>jQuery UI Datepicker - Default functionality</title> -->
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <!-- <link rel="stylesheet" href="/resources/demos/style.css"> -->
  

  
</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" style="margin-bottom: 10%">
  <img class="navbar-brand" src="{% static 'myapp\images\2.jpg' %}">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'myapp:block' %}">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="https://www.pec.ac.in/history">About</a>
   

    </div>
    <div class="navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      
        <li class='nav-item'>
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li> 
  
          
       </ul>
       </div>
  </div>
</nav>

<div class='container'>
<div class="jumbotron">
  <h1 class="display-4">Welcome To Reschedule Classes</h1>
  <p class="lead">This is a simple class reschedule. Please choose from the classes, or labs or tut rooms and select date u want to reschedule the class.!!!</p>

</div>
 <form action="{% url 'lecture' %}" method='POST'>
  {% csrf_token %}
<div class='container'>
    {% if messages %}
      <ul class='messages'>
        {% for message in messages %}
        {% if abc %}
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>{{message}}</strong> 
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% else %}
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>{{message}}</strong> 
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif %}
        {% endfor %}
      </ul>
    {% endif %}
    </div>
<div class='row'>
 <div class="card col-12 col-md-5  col-lg-3" style="width: 12rem;">
	<div class="container justify-content-center">
  <div class="card-body">
    <h5 class="card-title">Classes</h5>
    <p class="card-text">Select Date and Time</p>
  </div>

  <input type="hidden" name="blockname" value="{{block_is}}"> 
  <ul class="list-group list-group-flush">
  	<p>Date: <input type="text" name='date1' class="datepicker"></p>
  	</ul>
  <div>Time: 
  	<select name="time1">
  		<option value="1">8-9</option>
  		<option value="2">9-10</option>
  		<option value="3">10-11</option>
  		<option value="4">11-12</option>
  		<option value="5">12-1</option>
  		<option value="6">1-2</option>
  		<option value="7">2-3</option>
  		<option value="8">3-4</option>
  		<option value="9">4-5</option>
  	</select></div>
  	<div class='container abc' id='some'>
      
  		<button type='submit' name='L' value='Find' class='btn btn-success abc' >
  	   Find
      </button>
      <button type='submit' name='L_cancel' value='Cancel' class='btn btn-success abc' >
       Cancel
      </button>

  	</div>
 </div>
</div>

<div class="card col-12 col-md-5 col-lg-3 " style="width: 12rem;">
	<div class="container justify-content-center">
  <div class="card-body">
    <h5 class="card-title">Labs</h5>
    <p class="card-text">Select Date and Time</p>
  </div>
 
  <ul class="list-group list-group-flush">
  	<p>Date: <input type="text" name='date2' class="datepicker"></p>
  	</ul>
  <div>Time: 
  	<select name="time2">
  		<option value="1">8-9</option>
  		<option value="2">9-10</option>
  		<option value="3">10-11</option>
  		<option value="4">11-12</option>
  		<option value="5">12-1</option>
  		<option value="6">1-2</option>
  		<option value="7">2-3</option>
  		<option value="8">3-4</option>
  		<option value="9">4-5</option>
  	</select></div>
  	<div class='container abc' id='some'>
  		<button type='submit' name='A' value='Find' class='btn btn-success abc'  >
        Find
      </button>
      <button type='submit' name='A_cancel' value='Cancel' class='btn btn-success abc'  >
       Cancel
      </button>

  	</div>
 </div>
</div>
<div class="card col-12 col-md-5 col-lg-3 " style="width: 12rem;">
	<div class="container justify-content-center">
  <div class="card-body">
    <h5 class="card-title">Tut Rooms</h5>
    <p class="card-text">Select Date and Time</p>
  </div>
 
  <ul class="list-group list-group-flush">
  	<p>Date: <input type="text" name='date3' class="datepicker"></p>
  	</ul>
  <div>Time: 
  	<select name="time3">
  		<option value="1">8-9</option>
  		<option value="2">9-10</option>
  		<option value="3">10-11</option>
  		<option value="4">11-12</option>
  		<option value="5">12-1</option>
  		<option value="6">1-2</option>
  		<option value="7">2-3</option>
  		<option value="8">3-4</option>
  		<option value="9">4-5</option>
  	</select></div>
  	<div class='container abc' id='some'>
  		<button type='submit' name='T' value='Find' class='btn btn-success abc' >
        Find
      </button>
      <button type='submit' name='T_cancel' value='Cancel' class='btn btn-success abc' >
       Cancel
      </button>

   	</div>
 </div>
</div>
</div>
</form>

</div>
  



	
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( ".datepicker" ).datepicker();
  } );
  </script>
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script> -->

</body>
</html>

templates/myapp/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	 <link rel="stylesheet" type="text/css" href="{% static 'myapp\fontawesome-free-5.11.2-web\css\all.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/mystyle.css' %}">
	<title>Login</title>
	<!-- <style type="text/css">
		.container{
			padding-top:25%;
			padding-bottom: 50%;
		}
	</style> -->
</head>
<body style="background-image: url({% static 'myapp//images/IMG_20191112_163101.jpg' %})">
	<form action="{% url 'myapp:user_login' %}" method='post'>
		{% csrf_token %}
		<div class='container'>
		{% if messages %}
			<ul class='messages'>
				{% for message in messages %}
					<div class="alert alert-danger alert-dismissible fade show" role="alert">
  					<strong>{{message}}</strong> 
  					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    				<span aria-hidden="true">&times;</span>
  					</button>
					</div>
				{% endfor %}
			</ul>
		{% endif %}
		</div>
		<!-- <div class='d-flex justify-content-center align-items-end'> -->
			<div class='container d-flex justify-content-center'>
			<div class='card'>
				<div class='card-header'>
					<h2>SIGN IN</h2>
				</div>
				<div class='card-body'>
					<form>
						<div class='input-group form-group'>
							<div class='input-group-prepend'>
								<span class='input-group-text'>
									<i class="fas fa-user"></i>
								</span>
							</div>
							<input type='text' class='form-control' name='Username' placeholder='Username' required>
						</div>
						<div class='input-group form-group'>
							<div class='input-group-prepend'>
								<span class='input-group-text'>
									<i class="fas fa-unlock-alt"></i>
								</span>
							</div>
							<input type='password' class='form-control' name='Password' placeholder='Password' required>
						</div>
						<div class='form-group'>
							<input type='submit' value='Login' class='btn btn-success'>
						</div>
					</form>
				</div>
			</div>
		<!-- </div> -->
	</div>
	</form>




	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	</body>
</html>

templates/myapp/lab.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static 'myapp\bootstrap-4.3.1-dist\css\bootstrap.css' %}" >
	<link rel="stylesheet" type="text/css" href="{% static 'myapp\fontawesome-free-5.11.2-web\css\all.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'myapp\lab1.css' %}">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <img class="navbar-brand" src="{% static 'myapp\images\2.jpg' %}">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'myapp:block' %}">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="https://www.pec.ac.in/history">About</a>
      <!-- <a class="nav-item nav-link" href="#">Pricing</a> -->

    </div>
    <div class="navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      
        <li class='nav-item'>
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li> 
  
          
       </ul>
       </div>
  </div>
</nav>
{% if lab %}
<form action="{% url 'booking' %}" method='POST'>
{% csrf_token %}

<input type="hidden" name="day_is" value="{{day}}">
<input type="hidden" name="time_is" value="{{time}}">
<input type="hidden" name="hall_is" value="{{halls}}">
<input type="hidden" name="date_is" value="{{dates}}">
<input type="hidden" name="block_is" value="{{blocks}}">
<input type="hidden" name="button1" value="{{button}}">

<div class='container d-flex justify-content-center'>
 <div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{button}} your Lab</h5>
    <h6 class="card-subtitle mb-2 text-muted"></h6>
    <p class="card-text">Select any one of these available labs</p>
    <div>
    	<select name='lecture_hall'>
    		
    		{% for i in lab %}
    		<option value={{i.halls}}>{{i.halls}}</option>
    		{% endfor %}
    	</select></div>

   <div id='some'>
    <button class='btn btn-dark'>{{button}}</button>
   </div>

   </div>
 </div>
</div>
</form>

{% else %}

<div class='container d-flex justify-content-center'>
 <div class="card" style="width: 20rem;">
  <div class="card-body">
    <h1 class="card-title">Sorry</h1>
    <h1 class="card-subtitle mb-2 text-muted"></h1>
    <h1 class="card-text">No available Labs!!!</h1>
    </div>
  </div>
</div>

{% endif %}

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


</body>
</html>